// topps/cards.js
// Images go in topps/images/ folder named: 1952.jpg, 1953.jpg, etc.

window.TOPPS_CARDS = [
  { year: 1952, era: 'Golden Age',    desc: 'The original. Bold team colors, portrait-style art.' },
  { year: 1953, era: 'Golden Age',    desc: 'Hand-painted portraits. Collector favorite.' },
  { year: 1954, era: 'Golden Age',    desc: 'Clean two-tone design with action poses.' },
  { year: 1955, era: 'Golden Age',    desc: 'Horizontal layout, a Topps first.' },
  { year: 1956, era: 'Golden Age',    desc: 'Portrait + action photo combo.' },
  { year: 1957, era: 'Golden Age',    desc: 'First standard size cards. Clean white borders.' },
  { year: 1958, era: 'Golden Age',    desc: 'Yellow pennant design. Cheerful and iconic.' },
  { year: 1959, era: 'Golden Age',    desc: 'Two-photo layout. Very distinctive.' },
  { year: 1960, era: 'Golden Age',    desc: 'Baseball diamond graphic motif.' },
  { year: 1961, era: 'Silver Age',    desc: 'Green gradient with team pennants.' },
  { year: 1962, era: 'Silver Age',    desc: 'Wood grain border. Warm and classic.' },
  { year: 1963, era: 'Silver Age',    desc: 'Pennant-shaped team name banner.' },
  { year: 1964, era: 'Silver Age',    desc: 'Photo with bold team color backing.' },
  { year: 1965, era: 'Silver Age',    desc: 'Embossed pennant design.' },
  { year: 1966, era: 'Silver Age',    desc: 'Black border with colorful team banners.' },
  { year: 1967, era: 'Silver Age',    desc: 'High-contrast with distinctive striping.' },
  { year: 1968, era: 'Silver Age',    desc: 'Burlap/hatching texture background.' },
  { year: 1969, era: 'Silver Age',    desc: 'Color team initials. Bold and graphic.' },
  { year: 1970, era: 'Silver Age',    desc: 'Gray border, color team name stripe.' },
  { year: 1971, era: 'Silver Age',    desc: 'Iconic black border. Moody and dramatic.' },
  { year: 1972, era: 'Psychedelic',   desc: 'Wild burst of color. Most garish ever made.' },
  { year: 1973, era: 'Psychedelic',   desc: 'Faded color borders. 70s all the way.' },
  { year: 1974, era: 'Psychedelic',   desc: 'Dark color with circular photo crop.' },
  { year: 1975, era: 'Psychedelic',   desc: 'Two-color striped borders. Pure 1975.' },
  { year: 1976, era: 'Psychedelic',   desc: 'Bicentennial pennant design.' },
  { year: 1977, era: 'Transition',    desc: 'Clean portrait with color name block.' },
  { year: 1978, era: 'Transition',    desc: 'Yellow color band, team in pennant.' },
  { year: 1979, era: 'Transition',    desc: 'Pitcher/batter combo photo design.' },
  { year: 1980, era: 'Transition',    desc: 'Simple clean design. Era of restraint.' },
  { year: 1981, era: 'Transition',    desc: 'Red/blue/yellow color blocks.' },
  { year: 1982, era: 'Junk Wax',      desc: 'Color team border. Sharp and clean.' },
  { year: 1983, era: 'Junk Wax',      desc: 'Three-color stripes. Very 80s.' },
  { year: 1984, era: 'Junk Wax',      desc: 'Allstar banner style. Bold header.' },
  { year: 1985, era: 'Junk Wax',      desc: 'Color box around photo. Clean.' },
  { year: 1986, era: 'Junk Wax',      desc: 'Black borders, high gloss.' },
  { year: 1987, era: 'Junk Wax',      desc: 'Wood grain border returns. Fan favorite.' },
  { year: 1988, era: 'Junk Wax',      desc: 'Clean white with color team name.' },
  { year: 1989, era: 'Junk Wax',      desc: 'Gray border with pink team name. Unique.' },
  { year: 1990, era: 'Junk Wax',      desc: 'White with color team banner. Very clean.' },
  { year: 1991, era: 'Junk Wax',      desc: 'Solid color borders with white nameplate.' },
  { year: 1992, era: 'Junk Wax',      desc: 'Gold foil debut. Flashy.' },
  { year: 1993, era: 'Junk Wax',      desc: 'Full bleed photo with color bar.' },
  { year: 2000, era: 'Modern',        desc: 'Clean Topps Stadium Club influence.' },
  { year: 2006, era: 'Modern',        desc: 'Return to classic white border look.' },
  { year: 2008, era: 'Modern',        desc: 'Chrome-influenced clean design.' },
  { year: 2011, era: 'Modern',        desc: 'Diamond anniversary edition. Classic.' },
  { year: 2014, era: 'Modern',        desc: 'Sparkle foil. Color nameplate.' },
  { year: 2016, era: 'Modern',        desc: 'Color gradient design. Very popular.' },
  { year: 2019, era: 'Recent',        desc: 'Colorful swoosh design. Very popular.' },
  { year: 2020, era: 'Recent',        desc: 'Stadium-inspired design.' },
  { year: 2021, era: 'Recent',        desc: 'Modern minimal. Full-bleed photo.' },
  { year: 2022, era: 'Recent',        desc: 'Foil stripe. Clean and contemporary.' },
  { year: 2023, era: 'Recent',        desc: 'Bold diagonal design element.' },
  { year: 2024, era: 'Recent',        desc: 'Latest flagship. Full photo with color bar.' },
  { year: 2025, era: 'Recent',        desc: '2025 flagship design.' },
  { year: 2026, era: 'Recent',        desc: '2026 flagship design.' },
];
