// cards.js — Topps design years + metadata
// For each year, drop an image named e.g. "1952.jpg" into the /images/ folder.
// Image sourcing guide is in README.md.

const TOPPS_CARDS = [
  { year: 1952, name: "1952 Topps", description: "The original. Color painting on white, bold team name banner.", color: "#c8102e" },
  { year: 1953, name: "1953 Topps", description: "Portrait painting style, pastel backgrounds.", color: "#1a3a6b" },
  { year: 1954, name: "1954 Topps", description: "Two-photo design — action shot + portrait.", color: "#2d6a2d" },
  { year: 1955, name: "1955 Topps", description: "Horizontal layout debut. Circle portrait over action.", color: "#8b4513" },
  { year: 1956, name: "1956 Topps", description: "Horizontal, landscape photography, painted backgrounds.", color: "#4a4a8a" },
  { year: 1957, name: "1957 Topps", description: "Clean white borders, sharp photography replaces paintings.", color: "#1a1a2e" },
  { year: 1958, name: "1958 Topps", description: "Yellow name banner, yellow circle team name.", color: "#d4a017" },
  { year: 1959, name: "1959 Topps", description: "Colorful pennant design, player name in pennant.", color: "#c8102e" },
  { year: 1960, name: "1960 Topps", description: "Two-photo layout returns, baseball diamond motif.", color: "#2d6a2d" },
  { year: 1961, name: "1961 Topps", description: "Shield/crest design with team colors.", color: "#1a3a6b" },
  { year: 1962, name: "1962 Topps", description: "Wood grain border. Iconic Americana feel.", color: "#8b5e3c" },
  { year: 1963, name: "1963 Topps", description: "Color-coded by team, pennant flag detail.", color: "#c8102e" },
  { year: 1964, name: "1964 Topps", description: "Black and white inner frame, colorful outer.", color: "#1a1a1a" },
  { year: 1965, name: "1965 Topps", description: "Pennant-shaped team name banner.", color: "#2d6a2d" },
  { year: 1966, name: "1966 Topps", description: "Team color coded, angled text design.", color: "#4a4a8a" },
  { year: 1967, name: "1967 Topps", description: "Clean vertical layout, color matched borders.", color: "#8b4513" },
  { year: 1968, name: "1968 Topps", description: "Burlap/hatching texture background. Very distinctive.", color: "#5c4033" },
  { year: 1969, name: "1969 Topps", description: "White team name in colored circle, clean design.", color: "#c8102e" },
  { year: 1970, name: "1970 Topps", description: "Gray back, team color bold banner at top.", color: "#1a3a6b" },
  { year: 1971, name: "1971 Topps", description: "Black border. One of the most iconic designs ever.", color: "#111111" },
  { year: 1972, name: "1972 Topps", description: "Wild psychedelic comic-art borders. Very 70s.", color: "#e07b00" },
  { year: 1973, name: "1973 Topps", description: "Two-tone color border, clean modern look.", color: "#2d6a2d" },
  { year: 1974, name: "1974 Topps", description: "Large player name in team colors, minimal.", color: "#1a3a6b" },
  { year: 1975, name: "1975 Topps", description: "Two-color striped border — the most colorful ever made.", color: "#ff4136" },
  { year: 1976, name: "1976 Topps", description: "Bicentennial inspired, stars and stripes accents.", color: "#003087" },
  { year: 1977, name: "1977 Topps", description: "Star-shaped portrait cutout, team color field.", color: "#c8102e" },
  { year: 1978, name: "1978 Topps", description: "Yellow/white nameplate, clean photo presentation.", color: "#d4a017" },
  { year: 1979, name: "1979 Topps", description: "Comic-book style team name burst.", color: "#ff6b35" },
  { year: 1980, name: "1980 Topps", description: "Hat-shaped team logo bubble, gray borders.", color: "#4a4a8a" },
  { year: 1981, name: "1981 Topps", description: "Clean white borders return, team color corner.", color: "#1a1a1a" },
  { year: 1982, name: "1982 Topps", description: "Colorful diagonal stripe in corner.", color: "#2d6a2d" },
  { year: 1983, name: "1983 Topps", description: "Bold team color border, classic portrait style.", color: "#c8102e" },
  { year: 1984, name: "1984 Topps", description: "Black nameplate with team color accent.", color: "#111111" },
  { year: 1985, name: "1985 Topps", description: "Colorful inner border, open white outer.", color: "#1a3a6b" },
  { year: 1986, name: "1986 Topps", description: "Black border with team color vertical stripe.", color: "#1a1a1a" },
  { year: 1987, name: "1987 Topps", description: "WOOD GRAIN BORDER. The most nostalgic design ever.", color: "#8b5e3c" },
  { year: 1988, name: "1988 Topps", description: "Clean white, minimal team color accent.", color: "#1a3a6b" },
  { year: 1989, name: "1989 Topps", description: "Gray graduated background, bold name.", color: "#4a4a4a" },
  { year: 1990, name: "1990 Topps", description: "Gray grid pattern, bold team color stripe.", color: "#2d6a2d" },
  { year: 1991, name: "1991 Topps", description: "Team color inner border, gold outer.", color: "#d4a017" },
  { year: 1992, name: "1992 Topps", description: "Gold foil name/logo, clean photography.", color: "#c8a400" },
  { year: 1993, name: "1993 Topps", description: "Colorful inner frame, black outer. Bold.", color: "#c8102e" },
  { year: 1994, name: "1994 Topps", description: "Black inner border, team color accent.", color: "#111111" },
  { year: 1995, name: "1995 Topps", description: "Embossed foil design elements.", color: "#4a4a8a" },
  { year: 1996, name: "1996 Topps", description: "Full bleed photo, minimal overlay text.", color: "#1a1a1a" },
  { year: 1997, name: "1997 Topps", description: "Silver foil accents, clean full bleed.", color: "#8a8a8a" },
  { year: 1998, name: "1998 Topps", description: "Full bleed action, team color bottom strip.", color: "#1a3a6b" },
  { year: 1999, name: "1999 Topps", description: "Chrome-influenced clean design.", color: "#4a4a4a" },
  { year: 2000, name: "2000 Topps", description: "Millennium edition, bold foil Topps logo.", color: "#d4a017" },
  { year: 2001, name: "2001 Topps", description: "Action photography, minimal borders.", color: "#c8102e" },
  { year: 2002, name: "2002 Topps", description: "Team color banner, full bleed photo.", color: "#2d6a2d" },
  { year: 2003, name: "2003 Topps", description: "Clean white border returns with foil accents.", color: "#1a1a1a" },
  { year: 2004, name: "2004 Topps", description: "Black inner frame, color coded by team.", color: "#111111" },
  { year: 2005, name: "2005 Topps", description: "Retro-inspired design nods to 1955.", color: "#1a3a6b" },
  { year: 2006, name: "2006 Topps", description: "Clean, editorial full bleed photography.", color: "#4a4a4a" },
  { year: 2007, name: "2007 Topps", description: "Diagonal design element in corner.", color: "#c8102e" },
  { year: 2008, name: "2008 Topps", description: "Team color coded borders, bold name.", color: "#2d6a2d" },
  { year: 2009, name: "2009 Topps", description: "Clean white, modern editorial style.", color: "#1a1a1a" },
  { year: 2010, name: "2010 Topps", description: "Team color inner glow effect.", color: "#1a3a6b" },
  { year: 2011, name: "2011 Topps", description: "Diamond anniversary edition, elegant.", color: "#d4a017" },
  { year: 2012, name: "2012 Topps", description: "Clean two-tone team color design.", color: "#4a4a8a" },
  { year: 2013, name: "2013 Topps", description: "Curved team color banner at bottom.", color: "#c8102e" },
  { year: 2014, name: "2014 Topps", description: "Bold all-caps name, minimal design.", color: "#1a1a1a" },
  { year: 2015, name: "2015 Topps", description: "Team color inner border, clean white outer.", color: "#2d6a2d" },
  { year: 2016, name: "2016 Topps", description: "Silver foil all-caps name, team color accent.", color: "#8a8a8a" },
  { year: 2017, name: "2017 Topps", description: "Rainbow foil parallel introduced to base set aesthetic.", color: "#4a4a8a" },
  { year: 2018, name: "2018 Topps", description: "Clean, editorial. Blue team color accent.", color: "#1a3a6b" },
  { year: 2019, name: "2019 Topps", description: "150th anniversary of baseball on logo.", color: "#c8102e" },
  { year: 2020, name: "2020 Topps", description: "Blue foil accents, clean photography.", color: "#003087" },
  { year: 2021, name: "2021 Topps", description: "Silver foil, open white border design.", color: "#8a8a8a" },
  { year: 2022, name: "2022 Topps", description: "Team color inner frame, bold typography.", color: "#1a1a1a" },
  { year: 2023, name: "2023 Topps", description: "Clean modern design, bold name treatment.", color: "#c8102e" },
  { year: 2024, name: "2024 Topps", description: "Contemporary full bleed with team color bar.", color: "#1a3a6b" },
  { year: 2025, name: "2025 Topps", description: "Modern minimal design with bold typography.", color: "#c8102e" },
  { year: 2026, name: "2026 Topps", description: "Latest Topps flagship design.", color: "#2d6a2d" },
];

// Default Elo rating for all cards
const DEFAULT_ELO = 1500;

if (typeof module !== 'undefined') module.exports = { TOPPS_CARDS, DEFAULT_ELO };
