// movies/movies.js

window.MOVIES = [

  // ── 1970s ──────────────────────────────────────────────────────────────────
  { id: 'star-wars',              title: 'Star Wars',                           year: 1977, decade: '1970s', color: '#8B0000', desc: 'Changed movies forever. A farm boy, a princess, and a galaxy at war launched the blockbuster era.' },
  { id: 'jaws',                   title: 'Jaws',                                year: 1975, decade: '1970s', color: '#8B0000', desc: 'Spielberg invented the summer blockbuster. A great white shark terrorizes a beach town and nobody goes back in the water.' },
  { id: 'the-godfather',          title: 'The Godfather',                       year: 1972, decade: '1970s', color: '#8B0000', desc: 'The greatest American crime film ever made. A powerful mafia family navigates succession, loyalty, and betrayal in postwar New York.' },
  { id: 'the-godfather-ii',       title: 'The Godfather Part II',               year: 1974, decade: '1970s', color: '#8B0000', desc: 'One of the rare sequels that rivals the original. Two timelines show the rise and fall of the Corleone empire.' },
  { id: 'grease',                 title: 'Grease',                              year: 1978, decade: '1970s', color: '#8B0000', desc: 'The most rewatched musical of all time. Sandy and Danny fall in love at Rydell High and you know every word.' },
  { id: 'the-exorcist',           title: 'The Exorcist',                        year: 1973, decade: '1970s', color: '#8B0000', desc: 'Still the scariest film ever made. A young girl becomes possessed and two priests fight for her soul.' },
  { id: 'rocky',                  title: 'Rocky',                               year: 1976, decade: '1970s', color: '#8B0000', desc: 'The ultimate underdog story. A small-time Philadelphia boxer gets an impossible shot at the heavyweight title.' },
  { id: 'alien',                  title: 'Alien',                               year: 1979, decade: '1970s', color: '#8B0000', desc: 'Ridley Scott fused sci-fi and horror into something new. A spaceship crew encounters a perfect killing machine.' },
  { id: 'apocalypse-now',         title: 'Apocalypse Now',                      year: 1979, decade: '1970s', color: '#8B0000', desc: 'Coppola\'s Vietnam epic pushed filmmaking to its limits. A captain travels upriver to find a rogue colonel who has gone mad.' },
  { id: 'saturday-night-fever',   title: 'Saturday Night Fever',                year: 1977, decade: '1970s', color: '#8B0000', desc: 'The film that defined disco. A Brooklyn kid finds his identity on the dance floor while struggling to escape his neighborhood.' },
  { id: 'close-encounters',       title: 'Close Encounters of the Third Kind',  year: 1977, decade: '1970s', color: '#8B0000', desc: 'Spielberg at his most awe-inspiring. An ordinary man becomes obsessed with a vision and discovers Earth is not alone.' },

  // ── 1980s ──────────────────────────────────────────────────────────────────
  { id: 'et',                     title: 'E.T. the Extra-Terrestrial',          year: 1982, decade: '1980s', color: '#00008B', desc: 'The highest-grossing film of the decade. A lonely boy befriends a stranded alien and tries to help him get home.' },
  { id: 'empire-strikes-back',    title: 'The Empire Strikes Back',             year: 1980, decade: '1980s', color: '#00008B', desc: 'The best sequel ever made. The Rebel Alliance faces its darkest hour and Darth Vader reveals a devastating secret.' },
  { id: 'return-of-the-jedi',     title: 'Return of the Jedi',                 year: 1983, decade: '1980s', color: '#00008B', desc: 'The original trilogy\'s conclusion. Luke faces Vader and the Emperor while the Rebels attack the second Death Star.' },
  { id: 'raiders-of-the-lost-ark', title: 'Raiders of the Lost Ark',           year: 1981, decade: '1980s', color: '#00008B', desc: 'The perfect adventure film. Archaeologist Indiana Jones races the Nazis to find the biblical Ark of the Covenant.' },
  { id: 'the-shining',            title: 'The Shining',                         year: 1980, decade: '1980s', color: '#00008B', desc: 'Kubrick\'s horror masterpiece. A writer takes a winter caretaker job at an isolated hotel and slowly loses his mind.' },
  { id: 'scarface',               title: 'Scarface',                            year: 1983, decade: '1980s', color: '#00008B', desc: 'Al Pacino at maximum intensity. A Cuban immigrant claws his way to the top of Miami\'s drug empire.' },
  { id: 'batman-1989',            title: 'Batman',                              year: 1989, decade: '1980s', color: '#00008B', desc: 'Tim Burton made Gotham feel genuinely dark. The Caped Crusader faces the Joker in a gothic, stylized Gotham City.' },
  { id: 'ghostbusters',           title: 'Ghostbusters',                        year: 1984, decade: '1980s', color: '#00008B', desc: 'The funniest blockbuster of the decade. Three scientists start a ghost-catching business in New York City.' },
  { id: 'beverly-hills-cop',      title: 'Beverly Hills Cop',                   year: 1984, decade: '1980s', color: '#00008B', desc: 'Eddie Murphy at the peak of his powers. A Detroit detective investigates his friend\'s murder in Beverly Hills.' },
  { id: 'back-to-the-future',     title: 'Back to the Future',                  year: 1985, decade: '1980s', color: '#00008B', desc: 'The most perfectly constructed blockbuster script ever written. A teenager accidentally travels to 1955 and has to get back.' },
  { id: 'top-gun',                title: 'Top Gun',                             year: 1986, decade: '1980s', color: '#00008B', desc: 'The coolest movie of the decade. A hotshot Navy pilot trains at the elite fighter weapons school and falls for his instructor.' },
  { id: 'die-hard',               title: 'Die Hard',                            year: 1988, decade: '1980s', color: '#00008B', desc: 'Is it a Christmas movie? A New York cop battles terrorists in a Los Angeles skyscraper on Christmas Eve.' },
  { id: 'ferris-bueller',         title: "Ferris Bueller's Day Off",            year: 1986, decade: '1980s', color: '#00008B', desc: 'John Hughes at his best. A charismatic teenager fakes sick to spend one legendary day in Chicago with his best friends.' },

  // ── 1990s ──────────────────────────────────────────────────────────────────
  { id: 'titanic',                title: 'Titanic',                             year: 1997, decade: '1990s', color: '#4B0082', desc: 'The most successful film of its era. A first-class romance unfolds aboard the doomed ocean liner.' },
  { id: 'jurassic-park',          title: 'Jurassic Park',                       year: 1993, decade: '1990s', color: '#4B0082', desc: 'The moment CGI changed cinema forever. Scientists bring dinosaurs back to life and immediately lose control of them.' },
  { id: 'forrest-gump',           title: 'Forrest Gump',                        year: 1994, decade: '1990s', color: '#4B0082', desc: 'Won Best Picture and deeply divided audiences. A kind-hearted man from Alabama accidentally shapes decades of American history.' },
  { id: 'the-lion-king',          title: 'The Lion King',                       year: 1994, decade: '1990s', color: '#4B0082', desc: 'The pinnacle of Disney animation. A lion cub flees his kingdom after his father\'s murder and must reclaim his destiny.' },
  { id: 'goodfellas',             title: 'Goodfellas',                          year: 1990, decade: '1990s', color: '#4B0082', desc: 'Scorsese\'s masterpiece. A young man rises through the ranks of the New York mob over three decades.' },
  { id: 'silence-of-the-lambs',   title: 'The Silence of the Lambs',           year: 1991, decade: '1990s', color: '#4B0082', desc: 'The only horror film to win Best Picture. An FBI trainee enlists a brilliant cannibal to catch a serial killer.' },
  { id: 'schindlers-list',        title: "Schindler's List",                    year: 1993, decade: '1990s', color: '#4B0082', desc: 'Spielberg\'s most important film. A German businessman saves over a thousand Jewish lives during the Holocaust.' },
  { id: 'home-alone',             title: 'Home Alone',                          year: 1990, decade: '1990s', color: '#4B0082', desc: 'The highest-grossing comedy of its era. An eight-year-old is accidentally left behind and defends his house from burglars.' },
  { id: 'the-sixth-sense',        title: 'The Sixth Sense',                     year: 1999, decade: '1990s', color: '#4B0082', desc: 'The twist that broke the internet before the internet existed. A child psychologist tries to help a boy who sees dead people.' },
  { id: 'independence-day',       title: 'Independence Day',                    year: 1996, decade: '1990s', color: '#4B0082', desc: 'Pure 90s summer blockbuster. Aliens invade Earth and humanity fights back on the Fourth of July.' },
  { id: 'terminator-2',           title: 'Terminator 2: Judgment Day',          year: 1991, decade: '1990s', color: '#4B0082', desc: 'Set the standard for action sequels. The same Terminator sent to kill John Connor is now sent back to protect him.' },
  { id: 'men-in-black',           title: 'Men in Black',                        year: 1997, decade: '1990s', color: '#4B0082', desc: 'The perfect odd couple. A street cop joins a secret government agency that monitors alien activity on Earth.' },
  { id: 'the-matrix',             title: 'The Matrix',                          year: 1999, decade: '1990s', color: '#4B0082', desc: 'The Wachowskis rewired how we think about reality. A hacker discovers the world he lives in is a simulation.' },
  { id: 'pulp-fiction',           title: 'Pulp Fiction',                        year: 1994, decade: '1990s', color: '#4B0082', desc: 'Tarantino\'s masterpiece. Interconnected LA crime stories told out of order, with dialogue nobody has matched since.' },
  { id: 'aladdin',                title: 'Aladdin',                             year: 1992, decade: '1990s', color: '#4B0082', desc: 'Robin Williams as the Genie is one of the great vocal performances in film. A street thief falls for a princess with a magic lamp.' },
  { id: 'saving-private-ryan',    title: 'Saving Private Ryan',                 year: 1998, decade: '1990s', color: '#4B0082', desc: 'Redefined war films permanently. A squad of soldiers is sent to find and bring home the last surviving brother after D-Day.' },

  // ── 2000s ──────────────────────────────────────────────────────────────────
  { id: 'the-dark-knight',        title: 'The Dark Knight',                     year: 2008, decade: '2000s', color: '#014421', desc: 'The best superhero film ever made. Batman faces the Joker, a criminal who just wants to watch the world burn.' },
  { id: 'avatar',                 title: 'Avatar',                              year: 2009, decade: '2000s', color: '#014421', desc: 'The highest-grossing film of all time. A paraplegic marine infiltrates an alien civilization on a distant moon.' },
  { id: 'spider-man',             title: 'Spider-Man',                          year: 2002, decade: '2000s', color: '#014421', desc: 'Raimi launched the modern superhero era. A nerdy teenager bitten by a radioactive spider becomes a crime-fighting hero.' },
  { id: 'lotr-return-of-the-king', title: 'Lord of the Rings: Return of the King', year: 2003, decade: '2000s', color: '#014421', desc: 'Won all 11 Oscars it was nominated for. The final battle for Middle-earth as Frodo carries the Ring to Mount Doom.' },
  { id: 'harry-potter-1',         title: "Harry Potter and the Sorcerer's Stone", year: 2001, decade: '2000s', color: '#014421', desc: 'The franchise that defined the decade. An orphaned boy discovers he\'s a wizard and enrolls at Hogwarts School.' },
  { id: 'finding-nemo',           title: 'Finding Nemo',                        year: 2003, decade: '2000s', color: '#014421', desc: 'Pixar at their emotional peak. An overprotective clownfish crosses the ocean to find his missing son.' },
  { id: 'the-incredibles',        title: 'The Incredibles',                     year: 2004, decade: '2000s', color: '#014421', desc: 'The best superhero family film ever made. A retired superhero is forced back into action to save his family and the world.' },
  { id: 'wall-e',                 title: 'WALL-E',                              year: 2008, decade: '2000s', color: '#014421', desc: 'Pixar made a nearly silent love story set in a post-apocalyptic Earth. A trash-compacting robot falls for another robot.' },
  { id: 'gladiator',              title: 'Gladiator',                           year: 2000, decade: '2000s', color: '#014421', desc: 'Russell Crowe at his most commanding. A Roman general is betrayed, enslaved, and becomes a gladiator seeking revenge.' },
  { id: 'no-country-for-old-men', title: 'No Country for Old Men',              year: 2007, decade: '2000s', color: '#014421', desc: 'The Coen Brothers\' darkest film. A Texas hunter finds drug money and is hunted by the most terrifying villain in cinema.' },
  { id: 'the-departed',           title: 'The Departed',                        year: 2006, decade: '2000s', color: '#014421', desc: 'Scorsese finally got his Oscar. A cop infiltrates the mob while a mobster infiltrates the police — neither knows about the other.' },
  { id: 'there-will-be-blood',    title: 'There Will Be Blood',                 year: 2007, decade: '2000s', color: '#014421', desc: 'Daniel Day-Lewis\'s greatest performance. An oil prospector\'s ruthless ambition destroys everything around him.' },

  // ── 2010s ──────────────────────────────────────────────────────────────────
  { id: 'avengers-endgame',       title: 'Avengers: Endgame',                   year: 2019, decade: '2010s', color: '#2F2F2F', desc: 'The biggest cinematic event of the decade. Earth\'s heroes travel through time to undo Thanos\'s universe-altering snap.' },
  { id: 'black-panther',          title: 'Black Panther',                       year: 2018, decade: '2010s', color: '#2F2F2F', desc: 'A cultural phenomenon that transcended superhero movies. The king of Wakanda defends his nation and its vibranium from a dangerous challenger.' },
  { id: 'dark-knight-rises',      title: 'The Dark Knight Rises',               year: 2012, decade: '2010s', color: '#2F2F2F', desc: 'Nolan\'s divisive conclusion to his Batman trilogy. Eight years after Joker, a masked terrorist named Bane brings Gotham to its knees.' },
  { id: 'frozen',                 title: 'Frozen',                              year: 2013, decade: '2010s', color: '#2F2F2F', desc: 'Disney\'s biggest animated hit in decades. A princess journeys into the mountains to find her ice-powered sister before she freezes the kingdom.' },
  { id: 'inception',              title: 'Inception',                           year: 2010, decade: '2010s', color: '#2F2F2F', desc: 'Nolan made a blockbuster about consciousness. A thief who enters people\'s dreams is hired to plant an idea instead of steal one.' },
  { id: 'mad-max-fury-road',      title: 'Mad Max: Fury Road',                  year: 2015, decade: '2010s', color: '#2F2F2F', desc: 'The greatest action film of the decade. A woman smuggles enslaved wives across a post-apocalyptic wasteland in one relentless chase.' },
  { id: 'get-out',                title: 'Get Out',                             year: 2017, decade: '2010s', color: '#2F2F2F', desc: 'Jordan Peele turned horror into social commentary. A Black man visits his white girlfriend\'s family and discovers something deeply wrong.' },
  { id: 'interstellar',           title: 'Interstellar',                        year: 2014, decade: '2010s', color: '#2F2F2F', desc: 'Nolan sent us to space and made us cry about time. A NASA pilot leaves his family to search for a new home for humanity.' },
  { id: 'wolf-of-wall-street',    title: 'The Wolf of Wall Street',             year: 2013, decade: '2010s', color: '#2F2F2F', desc: 'DiCaprio\'s most electric performance. The true story of a stockbroker\'s rise and fall through excess, fraud, and greed.' },
  { id: 'parasite',               title: 'Parasite',                            year: 2019, decade: '2010s', color: '#2F2F2F', desc: 'The first non-English film to win Best Picture. A poor Korean family methodically infiltrates the lives of a wealthy one.' },

  // ── 2020s ──────────────────────────────────────────────────────────────────
  { id: 'top-gun-maverick',       title: 'Top Gun: Maverick',                   year: 2022, decade: '2020s', color: '#8B6914', desc: 'The best sequel in decades. Maverick trains a new generation of Top Gun pilots including the son of his dead best friend.' },
  { id: 'oppenheimer',            title: 'Oppenheimer',                         year: 2023, decade: '2020s', color: '#8B6914', desc: 'Nolan made a three-hour biopic about a bomb that won Best Picture. The father of the atomic bomb grapples with what he has unleashed.' },
  { id: 'barbie',                 title: 'Barbie',                              year: 2023, decade: '2020s', color: '#8B6914', desc: 'The most talked-about movie of 2023. Barbie leaves her perfect plastic world and confronts what it means to be human.' },
  { id: 'dune-part-two',          title: 'Dune: Part Two',                      year: 2024, decade: '2020s', color: '#8B6914', desc: 'Villeneuve finished what he started. Paul Atreides leads a desert rebellion to avenge his family and claim his destiny.' },

];
